apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCh3VAKDTz1NAWUQrNUcuNA9w9djgeVHjSju4NtM5Ye6HLaQGNKHhxdLxYztZrFI9i7vDOTkNQ7OfMBzsl5qApsFiLohxIG6d1oBuD2s/5Sc7hszcu/If4+p0pehQqJtCW5OSvfBQR9FMq29wXWJv2NnseVmxZ2jDrZKoFOE8mLPPqb+wCThpscXw5y9Ppf1AilJmf0B4xU2T/OR9DlE5ORH7yycmas2AhLRe2XDsaBgQpj1yQOjkcqS7MYifREHUuJwUhxICpI2Bm2hEDrKfJnu7u5m/27RcjlbOU+o6SRi3S/PCN9+NSPhqmr2yyYZ0xcrBbcW5DvftugDRCLB0rU69bpoTiY+vI26epy+lmAKDV0x5eDL5SGd7yuhbGSl/2KDjlpDq4ue9KesJCLAP6aBFcpfHkfkIVnXsX4jd5MiQxOpPO+MtzzH7A8oeprhEFMpQIemDBr0h7unGY+asP15XOgSWLPmR5aAQTbY6SF6rzKe82n7zmQG3JCk8YXgHZKqV+BwST1fAM/cCY/Kn+Srgy2BQE9XaMXrHWFyQDvaK5/stwxVNAi9J1CHIjID6hc7eX4aRMJ9bbvPz62rJmQ1ugx6bQpq+LdbZpdAW+TQxA/REZ6r0fVtzqoBdtpvabPcIF7BlnL8O25DvoWRmB/T71sRJq8mW/w2i/zSQZFphGYyIUoz3uFvz5/mYjWkhnhdRqllNjdqY4xMP9pDuGee/q4hw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
